[book]
language     = "en"
multilingual = false
src          = "docs"

[output.html]
fold.enable          = true
additional-css       = [ "css/chapters.css", "css/root.css" ]
default-theme        = "coal"
preferred-dark-theme = "coal"
no-section-label     = true
git-repository-url   = "https://github.com/a1994sc/documents/tree/main"
edit-url-template    = "https://github.com/a1994sc/documents/edit/main/{path}"

[output.html.search]
limit-results       = 20
use-boolean-and     = true
boost-title         = 2
boost-hierarchy     = 2
boost-paragraph     = 1
expand              = true
heading-split-level = 2

[output.html.print]
page-break = true # insert page-break after each chapter
# enable     = true # include support for printable output
